- building_user_login_system-master/finish/app.py
> fix issue 77 - may not be root cause - but it is a resiliency fix

- building_user_login_system-master/finish/app.py
Addresses only part of #56 specifically two bugs related to sharing a project to a user and letting that user access the shared project.
> Partially fix sharing bugs

- templates/evaluation_page.html
Deleted the "Some message" in the file "evaluation_page.html"
> Deleted "Some message"

- templates/evaluation_page.html
Changed a few styles to make each block has some space between each other, fixed #151
> Fixed #151

- templates/evaluation_page.html
Fixed  #152 by changing the format for each li value
> Fixed #152

- templates/evaluation_page.html
Changed from Show Suggestion to Show Lists, fixed #153
> Fixed #153

- templates/evaluation_page.html
Fixed-#160, changed the highlighted issue by fixing the class for the group that has been chosen
> Fixed-#160

- templates/project_profile_jumptool.html
Fixed #166 Connect the link in Manage Rubric into the correct link in load project
> Fixed-#166

- templates/parent_login.html
- templates/parent_signed_in.html
Fixed #164  Changed names for website
> Changed names for website

- templates/evaluation_page.html
Get rid of the + blank tab in the evaluation page to make less confusion
> Deleted the + blank tab

- templates/parent_signed_in.html
Deleted the link for the title on the top left
> Deleted the link for the title on the top left

- templates/account.html
- templates/create_project.html
- templates/evaluation_page.html
- templates/instructor_project.html
- templates/project.html
- templates/project_profile.html
- templates/project_profile_jumptool.html
Deleted the link for Home button
> Deleted the link for Home button

- templates/project_profile.html
> deal with spaces by putting quotes around onclick's value

- templates/account.html
- templates/create_project.html
- templates/evaluation_page.html
- templates/instructor_project.html
- templates/project.html
- templates/project_profile.html
- templates/project_profile_jumptool.html
Fixed #170 Deleted all the links in the Breadcrumb and also make the style of all page the same.
> Fixed #170 - Changed the style of Breadcrumb

- templates/evaluation_page.html
Fixed #173  Deleted the Comment and the "Cancel" button
> Fixed #173 - Deleted the Comment and the "Cancel" button

- app.py
- templates/login.html
- templates/signup.html
Fixed #187 & #186 by adding the CheckPassword feature and changed a few names
> Fixed #187 & #186 - Add a CheckPassword for sign in page

- templates/evaluation_page.html
Fixed issue #190 by changing it's class's format and adding a margin. Now it's even much beautiful than before
> Fixed issue #190

- app.py
- templates/project_profile.html
Fixed #194 by fixing the style and changing the discription from Username into Email
> Fixed #194

- tests/test5_sharing.py
The test was missing the main function. This has been corrected.
> Added main function to test5_sharing.py

- tests/test6_account.py
- Using find() method to search sub-string in title we are looking for as the full title isn't needed for testing of the tested functionality
- Removes the need to reinitialize the database in order to fully test the functionality
> Changes to test6

- core/templates/evaluation_page.html
removed console.log(listOfgroups) to print the list of groups to the console, not needed.
> console.log removal

- core/templates/instructor_dashboard.html
replaced nav-body in instructor_dashboard with link to css
> instructor_dashboard nav-body

- core/templates/evaluation_page.html
the item with the ID logo does not exist therefore its not needed.
> menu removal

- core/templates/evaluation_page.html
reming group links, not needed
> group link removal

- core/templates/instructor_project.html
replaced nav-body in instructor_project with link to css
> instructor_project nav-body

- tests/sharingDriver.py
- tests/test5_sharing.py
Added necessary functions in driver to set up for the first test in sharingDriver.py! Added test1 that checks if the project name link works to test5_sharing.py! Removed unnecessary imports in sharingDriver.py!
> 298 test5 sharingpy test1 checking project name link works

- README.md
- core/tests/sharingDriver.py
- core/tests/test2_createProject_test.py
- core/tests/test3_evaluation_test.py
- core/tests/test4_rating_test.py
- core/tests/test5_sharing.py
- core/tests/test6_account.py
- dbcreate.py
- setupEnv.py
A new seupEnv.py file was in the works which takes care of setting up a devs environment in the new backend setup. Additionally, the README.md was updated to address the difference in command line syntax for users in either Windows or *nix systems.
> Updated Environment Setup and README.md updates

- core/templates/create_project.html
> Link updated

- BackEndFlask/models/course.py
- BackEndFlask/models/instructortacourse.py
> added instructortacourse.py

- BackEndFlask/README.md
Updated the documentation for the BackEnd server. 
The README.md now discusses how to setup the BackEnd server.
> Doc update

- FrontEndReact/.env
- FrontEndReact/package-lock.json
- FrontEndReact/package.json
- FrontEndReact/src/App.js
- FrontEndReact/src/View/Admin/Add/AddCourse/AdminAddCourse.js
- FrontEndReact/src/View/Admin/Add/AddTask/AdminAddAssessmentTask.js
- FrontEndReact/src/View/Admin/Add/AddTeam/AdminAddTeam.js
- FrontEndReact/src/View/Admin/Add/AddTeam/AdminTeamBulkUpload.js
- FrontEndReact/src/View/Admin/Add/AddUsers/AdminAddUser.js
- FrontEndReact/src/View/Admin/Add/AddUsers/AdminStudentBulkUpload.js
- FrontEndReact/src/View/Admin/View/CompleteAssessmentTask/CompleteAssessmentTask.js
- FrontEndReact/src/View/Admin/View/CompleteAssessmentTask/Section.js
- FrontEndReact/src/View/Admin/View/ViewAssessmentTask/AdminViewAssessmentTask.js
- FrontEndReact/src/View/Admin/View/ViewCompleteAssessmentTasks/AdminViewCompleteAssessmentTasks.js
- FrontEndReact/src/View/Admin/View/ViewConsent/AdminViewConsent.js
- FrontEndReact/src/View/Admin/View/ViewConsent/ViewConsent.js
- FrontEndReact/src/View/Admin/View/ViewCourses/AdminViewCourses.js
- FrontEndReact/src/View/Admin/View/ViewTeamMembers/AdminViewTeamMembers.js
- FrontEndReact/src/View/Admin/View/ViewTeams/AdminViewTeams.js
- FrontEndReact/src/View/Admin/View/ViewUsers/AdminViewUsers.js
- FrontEndReact/src/View/Student/View/StudentViewAssessmentTask.js
- FrontEndReact/src/View/Student/View/StudentViewTeams.js
- FrontEndReact/src/View/Student/View/Team/StudentTeamMembers.js
Added .env file with variable REACT_APP_API_URL to store URL of API. 
Create and exported variable API_URL from app.js to make it easily accessible from the rest of the program. Not entirely nessecrary, but I choose to this since it reads much nicer than process.env.REACT_APP_API_URL. 
Modified fetch calls throughout the frontend to use API_URL variable.
> Constant URL stored as an enviroment variable now used for fetch requests

- BackEndFlask/controller/Routes/Assessment_task_routes.py
- BackEndFlask/controller/Routes/Completed_assessment_routes.py
- BackEndFlask/controller/Routes/Course_routes.py
- BackEndFlask/controller/Routes/Role_routes.py
- BackEndFlask/controller/Routes/Rubric_routes.py
- BackEndFlask/controller/Routes/Student_bulk_upload_routes.py
- BackEndFlask/controller/Routes/Team_bulk_upload_routes.py
- BackEndFlask/controller/Routes/Team_routes.py
- BackEndFlask/controller/Routes/User_routes.py
- BackEndFlask/core/__init__.py
- BackEndFlask/models/schemas.py
- BackEndFlask/requirements.txt
- FrontEndReact/src/View/Admin/View/ViewAssessmentTask/ViewAssessmentTasks.js
Upon creating a new virtual machine running Ubuntu 64-bit 22.04.3 to check cross-platform compatibility for development, I encountered issues while attempting to run the Backend Flask Server. I have fixed these issues and now the Backend Flask Server runs as expected. I can confirm the changes I made to the Backend Flask Server work with MacOS as well. However, I do not have confirmation for Windows. Once I have a confirmation for Windows, we can merge the changes I made to master!
> Updating requirements.txt

- BackEndFlask/setupEnv.py
The rewrite for setupEnv.py. Supported flags are:
* -h, --help -> shows the usage
* -r, --reset -> resets the db
* -i, --install -> installs deps
* -s, --start -> starts flask
* -d, --demo -> loads demo.
> added the rewrite for setupEnv2.py

- BackEndFlask/models/logger.py
Added the ability to log messages/errors.
> Added logger implementation and logs/ directory.

- BackEndFlask/controller/Routes/Checkin_routes.py
- BackEndFlask/controller/Routes/Team_routes.py
- BackEndFlask/controller/__init__.py
- BackEndFlask/models/checkin.py
- BackEndFlask/models/schemas.py
* the teams table is now for storing default teams in a fixed team scenario 
* added Checkin table for users to checkin to a team for an assessment task. 
* added route to checkin in a user
* removed outdated commented out code
> Checkin and default team

- BackEndFlask/controller/Routes/Rubric_routes.py
- BackEndFlask/models/queries.py
- FrontEndReact/src/View/Admin/Add/AddCustomRubric/AdminAddCustomRubric.js
Tasks Completed:
- Added logic to check if the default flag is present to only retrieve the default rubrics. Otherwise, retrieve the default rubrics and the custom rubrics for the logged in user.
- Passed the default query parameter to the genericResourceGET() in the AdminAddCustomRubric.js.
> Skil 249 franken rubric fixes and improvements

- BackEndFlask/Functions/customExceptions.py
- BackEndFlask/Functions/genericImport.py
- BackEndFlask/Functions/helper.py
- BackEndFlask/models/user.py
- FrontEndReact/src/View/Admin/Add/AddUsers/AdminBulkUpload.js
This fix address three issues:
1. Students added via bulk upload (genericImport) would not receive emails
2. genericImport now expects the role to be either "student" or "TA" (capitalization does not matter)
3. Newlines are now accepted in student bulk upload
I have also updated AdminBulkUpload.js to reflect the new changes for the student bulk upload.
> Bulk upload email bugfix

- BackEndFlask/Functions/genericImport.py
This branch fixes the issue where if there was an error in the csv file, it would still upload students to the DB when it shouldn't. This solves it by putting them into a simple queue and then iterates adding each student stored in it after all parsing has been done.
> Bulk upload queue fix

- FrontEndReact/src/View/Admin/View/CompleteAssessmentTask/CompleteAssessmentTask.js
Modified componentDidUpdate call!
> SKIL-302 User_id error 

- BackEndFlask/models/user.py
- FrontEndReact/src/View/Admin/Add/AddUsers/AdminAddUser.js
This will turn on superadmins is_admin column to true allowing it to pass admincheck()
> Fixing superadmin

- BackEndFlask/controller/Routes/Rating_routes.py
TODO:
Removed an admin check to allow the student to view the completed assessments instead of getting kicked.
> FixStudentCompletedAssessmentView

- FrontEndReact/src/JestTestDocumentation.md
TODOs Completed:
- Created jest test documentation for new users to refer to how testing works for Skillbuilder.
> testing-documentation

- BackEndFlask/Functions/threads.py
- BackEndFlask/core/__init__.py
- BackEndFlask/gentok.sh
- BackEndFlask/models/utility.py
This fixes the emails not working due to a `return None` debug statement. I have also added `gentok.sh` to automate the token creation process.
> Auto token

- BackEndFlask/requirements.txt
---
- Requirements.txt is updated with both comments and now locks to a certain version for each lib
- Pip freeze was used to also lock down transitive libs
> locked down dependncies

- .github/workflows/ci.yml
- BackEndFlask/dependency_check.py
- BackEndFlask/setupEnv.py
---
1. CI now has a small comparison check on what back-end libs its working with compared to whats desired.
2. Backend now logs and outputs to the terminal libs that are out of data as a warning
**The backend file that was added was designed to work with the lock_down_dependencies branch**
> Better lib logging

- BackEndFlask/controller/security/CustomDecorators.py
more logging for the add_course issue.
> more logging
